tazama-lf/typology-processor

package.json, src/clients/redis.ts, src/config.ts, src/logic.service.ts
+ Added addOneGetAll redis function
+ Migrated from node-redis v3 to ioredis v5
+ Optimize executeRequset call using new redis functions
=> Redis optimizations

.env.template, dockerfile, src/logic.service.ts
Changed Typology Processor to use the value in the networkmap apposed to the one in the .env / dockerfile. 
In relation to issue : General-Issues # 17 ([The typology processor does not reference the network map when posting its results](https://github.com/frmscoe/General-Issues/issues/17))
=> Communication Through networkmap

src/classes/cadp-request.ts, src/logic.service.ts, yarn.lock
this feature adds the attribute of duration it took the tp to process.
Related to https://github.com/frmscoe/General-Issues/issues/153
=> feat: performance calculation

jest.config.ts, src/interfaces/metaData.ts, src/logic.service.ts
Related to https://github.com/frmscoe/General-Issues/issues/178
=> feat: send traceParent to next processor in chain

__tests__/unit/logic.service.test.ts, src/logic.service.ts
Related: frmscoe/General-Issues#202
=> Asynchronous processing

jest.config.ts, src/logic.service.ts
https://github.com/frmscoe/General-Issues/issues/208
=> bug: always end spans when error happens

Dockerfile, jest.config.ts, package-lock.json, package.json, src/apm.ts, src/clients/arango.ts, src/index.ts, src/logic.service.ts
Related to: https://github.com/frmscoe/General-Issues/issues/178
=> fix: autospans for supported technologies

Dockerfile
Related to https://github.com/frmscoe/General-Issues/issues/220
=> fix: upgrading node version to v20 for docker img

__tests__/unit/logic.service.test.ts, jest.config.ts, package-lock.json, package.json, src/logic.service.ts
Count has o(1) complexity and members o(n), so for most requests it should be much faster at load.
Related to https://github.com/frmscoe/frms-coe-lib/pull/47
=> feat: Use Count from Redis instead of Members

.env.template, Dockerfile, src/config.ts
Related to https://github.com/frmscoe/General-Issues/issues/225
=> fix: remove unused, comment and use FQDN

src/index.ts
In Relation to : https://github.com/frmscoe/General-Issues/issues/248
=> bug: fixed numCPUs

__tests__/unit/logic.service.test.ts, package-lock.json, package.json, src/logic.service.ts
Related to https://github.com/frmscoe/General-Issues/issues/232
Fix test, bug presented when desc attribute was no longer optional
https://github.com/frmscoe/frms-coe-lib/pull/62/files
=> Weight rule

__tests__/unit/logic.service.test.ts, package-lock.json, package.json, src/index.ts, src/logic.service.ts
Related to https://github.com/frmscoe/General-Issues/issues/263
=> Protobuf redis2

__tests__/unit/logic.service.test.ts, src/index.ts
Related: https://github.com/frmscoe/General-Issues/issues/277
=> Standardize db manager startup

__tests__/unit/logic.service.test.ts, package-lock.json, package.json, src/logic.service.ts
Related to: https://github.com/frmscoe/General-Issues/issues/281
=> Remove desc from typology result

.dockerignore, .editorconfig, .env.template, .eslintignore, .eslintrc.js, .gitignore, .npmrc, .prettierignore, .sonarcloud.properties, __tests__/__mocks__/arango.js, __tests__/__mocks__/ioredis.js, __tests__/unit/logic.service.test.ts, cluster-setup.ts, deployment.yaml, docker-compose.yaml, jest.config.ts, service.yaml, src/apm.ts, src/config.ts, src/index.ts, src/interfaces/iTypologyExpression.ts, src/interfaces/metaData.ts, src/logic.service.ts, src/services/services.ts
Related to https://github.com/frmscoe/General-Issues/issues/115
=> Add licensing

__tests__/unit/logic.service.test.ts, package-lock.json, package.json, src/interfaces/iTypologyExpression.ts, src/logic.service.ts
In Relation: https://github.com/frmscoe/General-Issues/issues/15
=> Feat add thresholds

Dockerfile, package.json
Package version change for release version
=> chore: Bump version for release

src/logic.service.ts
Adding the minimizing of transaction objects to other send of result
=> fix: minimizing the transaction object

src/utils/networkMapSetUpRoute.ts
add change rule request to rule response
=> fix: change ruleRequest to ruleResponse

README.md, __tests__/unit/logic.service.test.ts, package-lock.json, package.json, src/config.ts, src/interfaces/iTypologyExpression.ts, src/logic.service.ts, src/utils/evaluateTExpression.ts, tsconfig.json
=> Remove channels and replace ruleresults true/false with weights

src/logic.service.ts
In Relation to: https://github.com/frmscoe/typology-processor/issues/201
=> feat: fixed duplicate nats messages

README.md, __tests__/unit/logic.service.test.ts, package-lock.json, package.json, src/config.ts, src/index.ts, src/interfaces/iTypologyExpression.ts, src/utils/evaluateTExpression.ts
=> feat: use MathJSON to evaluate Typology expressions

README.md, __tests__/unit/logic.service.test.ts, src/interfaces/iTypologyExpression.ts, src/logic.service.ts, src/utils/evaluateTExpression.ts
1. Typology configuration 
2. Typology processor mainly typology evaluation algorithm
1. To reduce data duplication.
=> refactor: From mathjson simplify wght

package-lock.json, package.json
=> build: update lib versions

src/index.ts
Enabled the interdiction producer subject
To accept the subject from the environment variable
=> fix: set interdiction producer

.env.template, Dockerfile, __tests__/unit/logic.service.test.ts, package-lock.json, package.json, src/apm.ts, src/config.ts, src/index.ts
=> refactor: env validation

__tests__/unit/logic.service.test.ts, cluster-setup.ts, package-lock.json, package.json, src/apm.ts, src/config.ts, src/index.ts, src/logic.service.ts, src/services/services.ts
Encapsulate service config in lib
=> refactor: abstract service configs

README.md, cluster-setup.ts, package-lock.json, package.json
Add Multi-currency support in dataCache for NATS communication (dependencies)
=> feat: add multi-currency dataCache support

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/development-item.md, .github/ISSUE_TEMPLATE/failing-tests.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/workflows/dockerhub-image-build-rc.yml, .github/workflows/dockerhub-image-build.yml, .github/workflows/njsscan.yml
Test multi-tenancy - update dependencies, versions, workflows and skip Dependabot triggers
E2E testing
=> feat: Test multi-tenancy - update dependencies, versions, workflows and skip Dependabot triggers
